query {
  familyEqualTo_4: allFilterables(zzz_filter: { inet: { zzz_familyEqualTo: 4 } }) {
    ...nodes
  }
  familyEqualTo_6: allFilterables(zzz_filter: { inet: { zzz_familyEqualTo: 6 } }) {
    ...nodes
  }
  familyNotEqualTo_4: allFilterables(zzz_filter: { inet: { zzz_familyNotEqualTo: 4 } }) {
    ...nodes
  }
  familyNotEqualTo_6: allFilterables(zzz_filter: { inet: { zzz_familyNotEqualTo: 6 } }) {
    ...nodes
  }
  isV4_true: allFilterables(zzz_filter: { inet: { zzz_isV4: true } }) {
    ...nodes
  }
  isV4_false: allFilterables(zzz_filter: { inet: { zzz_isV4: false } }) {
    ...nodes
  }
}

fragment nodes on FilterablesConnection {
  nodes {
    id
  }
}
