query bpchar4Array(
  $v2: [String] = ["Test", "tEST"]
  $v2_1: String = "Test"
  $v3: [String] = ["tEST", "test"]
) {
  anyEqualTo: allArrayTypes(zzz_filter: { bpchar4Array: { zzz_anyEqualTo: $v2_1 } }) {
    ...nodes
  }
  anyGreaterThan: allArrayTypes(
    zzz_filter: { bpchar4Array: { zzz_anyGreaterThan: $v2_1 } }
  ) {
    ...nodes
  }
  anyGreaterThanOrEqualTo: allArrayTypes(
    zzz_filter: { bpchar4Array: { zzz_anyGreaterThanOrEqualTo: $v2_1 } }
  ) {
    ...nodes
  }
  anyLessThan: allArrayTypes(zzz_filter: { bpchar4Array: { zzz_anyLessThan: $v2_1 } }) {
    ...nodes
  }
  anyLessThanOrEqualTo: allArrayTypes(
    zzz_filter: { bpchar4Array: { zzz_anyLessThanOrEqualTo: $v2_1 } }
  ) {
    ...nodes
  }
  anyNotEqualTo: allArrayTypes(
    zzz_filter: { bpchar4Array: { zzz_anyNotEqualTo: $v2_1 } }
  ) {
    ...nodes
  }
  containedBy: allArrayTypes(zzz_filter: { bpchar4Array: { zzz_containedBy: $v2 } }) {
    ...nodes
  }
  contains: allArrayTypes(zzz_filter: { bpchar4Array: { zzz_contains: $v3 } }) {
    ...nodes
  }
  distinctFrom: allArrayTypes(zzz_filter: { bpchar4Array: { zzz_distinctFrom: $v2 } }) {
    ...nodes
  }
  equalTo: allArrayTypes(zzz_filter: { bpchar4Array: { zzz_equalTo: $v2 } }) {
    ...nodes
  }
  greaterThan: allArrayTypes(zzz_filter: { bpchar4Array: { zzz_greaterThan: $v2 } }) {
    ...nodes
  }
  greaterThanOrEqualTo: allArrayTypes(
    zzz_filter: { bpchar4Array: { zzz_greaterThanOrEqualTo: $v2 } }
  ) {
    ...nodes
  }
  isNull: allArrayTypes(zzz_filter: { bpchar4Array: { zzz_isNull: true } }) {
    ...nodes
  }
  lessThan: allArrayTypes(zzz_filter: { bpchar4Array: { zzz_lessThan: $v2 } }) {
    ...nodes
  }
  lessThanOrEqualTo: allArrayTypes(
    zzz_filter: { bpchar4Array: { zzz_lessThanOrEqualTo: $v2 } }
  ) {
    ...nodes
  }
  notDistinctFrom: allArrayTypes(
    zzz_filter: { bpchar4Array: { zzz_notDistinctFrom: $v2 } }
  ) {
    ...nodes
  }
  notEqualTo: allArrayTypes(zzz_filter: { bpchar4Array: { zzz_notEqualTo: $v2 } }) {
    ...nodes
  }
  overlaps: allArrayTypes(zzz_filter: { bpchar4Array: { zzz_overlaps: $v2 } }) {
    ...nodes
  }
}

fragment nodes on ArrayTypesConnection {
  nodes {
    id
  }
}
