query macaddrArray(
  $v2: [MacAddress] = [
    "00:00:00:00:00:02"
    "00:00:00:00:00:03"
  ]
  $v2_1: MacAddress = "00:00:00:00:00:02"
  $v3: [MacAddress] = [
    "00:00:00:00:00:03"
    "00:00:00:00:00:04"
  ]
) {
  anyEqualTo: allArrayTypes(zzz_filter: { macaddrArray: { zzz_anyEqualTo: $v2_1 } }) {
    ...nodes
  }
  anyGreaterThan: allArrayTypes(
    zzz_filter: { macaddrArray: { zzz_anyGreaterThan: $v2_1 } }
  ) {
    ...nodes
  }
  anyGreaterThanOrEqualTo: allArrayTypes(
    zzz_filter: { macaddrArray: { zzz_anyGreaterThanOrEqualTo: $v2_1 } }
  ) {
    ...nodes
  }
  anyLessThan: allArrayTypes(zzz_filter: { macaddrArray: { zzz_anyLessThan: $v2_1 } }) {
    ...nodes
  }
  anyLessThanOrEqualTo: allArrayTypes(
    zzz_filter: { macaddrArray: { zzz_anyLessThanOrEqualTo: $v2_1 } }
  ) {
    ...nodes
  }
  anyNotEqualTo: allArrayTypes(
    zzz_filter: { macaddrArray: { zzz_anyNotEqualTo: $v2_1 } }
  ) {
    ...nodes
  }
  containedBy: allArrayTypes(zzz_filter: { macaddrArray: { zzz_containedBy: $v2 } }) {
    ...nodes
  }
  contains: allArrayTypes(zzz_filter: { macaddrArray: { zzz_contains: $v3 } }) {
    ...nodes
  }
  distinctFrom: allArrayTypes(zzz_filter: { macaddrArray: { zzz_distinctFrom: $v2 } }) {
    ...nodes
  }
  equalTo: allArrayTypes(zzz_filter: { macaddrArray: { zzz_equalTo: $v2 } }) {
    ...nodes
  }
  greaterThan: allArrayTypes(zzz_filter: { macaddrArray: { zzz_greaterThan: $v2 } }) {
    ...nodes
  }
  greaterThanOrEqualTo: allArrayTypes(
    zzz_filter: { macaddrArray: { zzz_greaterThanOrEqualTo: $v2 } }
  ) {
    ...nodes
  }
  isNull: allArrayTypes(zzz_filter: { macaddrArray: { zzz_isNull: true } }) {
    ...nodes
  }
  lessThan: allArrayTypes(zzz_filter: { macaddrArray: { zzz_lessThan: $v2 } }) {
    ...nodes
  }
  lessThanOrEqualTo: allArrayTypes(
    zzz_filter: { macaddrArray: { zzz_lessThanOrEqualTo: $v2 } }
  ) {
    ...nodes
  }
  notDistinctFrom: allArrayTypes(
    zzz_filter: { macaddrArray: { zzz_notDistinctFrom: $v2 } }
  ) {
    ...nodes
  }
  notEqualTo: allArrayTypes(zzz_filter: { macaddrArray: { zzz_notEqualTo: $v2 } }) {
    ...nodes
  }
  overlaps: allArrayTypes(zzz_filter: { macaddrArray: { zzz_overlaps: $v2 } }) {
    ...nodes
  }
}

fragment nodes on ArrayTypesConnection {
  nodes {
    id
  }
}
