query timestamptzArray(
  $v2: [Datetime] = ["1999-02-01 00:00", "1999-03-01 00:00"]
  $v2_1: Datetime = "1999-02-01 00:00"
  $v3: [Datetime] = ["1999-03-01 00:00", "1999-04-01 00:00"]
) {
  anyEqualTo: allArrayTypes(
    zzz_filter: { timestamptzArray: { zzz_anyEqualTo: $v2_1 } }
  ) {
    ...nodes
  }
  anyGreaterThan: allArrayTypes(
    zzz_filter: { timestamptzArray: { zzz_anyGreaterThan: $v2_1 } }
  ) {
    ...nodes
  }
  anyGreaterThanOrEqualTo: allArrayTypes(
    zzz_filter: { timestamptzArray: { zzz_anyGreaterThanOrEqualTo: $v2_1 } }
  ) {
    ...nodes
  }
  anyLessThan: allArrayTypes(
    zzz_filter: { timestamptzArray: { zzz_anyLessThan: $v2_1 } }
  ) {
    ...nodes
  }
  anyLessThanOrEqualTo: allArrayTypes(
    zzz_filter: { timestamptzArray: { zzz_anyLessThanOrEqualTo: $v2_1 } }
  ) {
    ...nodes
  }
  anyNotEqualTo: allArrayTypes(
    zzz_filter: { timestamptzArray: { zzz_anyNotEqualTo: $v2_1 } }
  ) {
    ...nodes
  }
  containedBy: allArrayTypes(
    zzz_filter: { timestamptzArray: { zzz_containedBy: $v2 } }
  ) {
    ...nodes
  }
  contains: allArrayTypes(zzz_filter: { timestamptzArray: { zzz_contains: $v3 } }) {
    ...nodes
  }
  distinctFrom: allArrayTypes(
    zzz_filter: { timestamptzArray: { zzz_distinctFrom: $v2 } }
  ) {
    ...nodes
  }
  equalTo: allArrayTypes(zzz_filter: { timestamptzArray: { zzz_equalTo: $v2 } }) {
    ...nodes
  }
  greaterThan: allArrayTypes(
    zzz_filter: { timestamptzArray: { zzz_greaterThan: $v2 } }
  ) {
    ...nodes
  }
  greaterThanOrEqualTo: allArrayTypes(
    zzz_filter: { timestamptzArray: { zzz_greaterThanOrEqualTo: $v2 } }
  ) {
    ...nodes
  }
  isNull: allArrayTypes(zzz_filter: { timestamptzArray: { zzz_isNull: true } }) {
    ...nodes
  }
  lessThan: allArrayTypes(zzz_filter: { timestamptzArray: { zzz_lessThan: $v2 } }) {
    ...nodes
  }
  lessThanOrEqualTo: allArrayTypes(
    zzz_filter: { timestamptzArray: { zzz_lessThanOrEqualTo: $v2 } }
  ) {
    ...nodes
  }
  notDistinctFrom: allArrayTypes(
    zzz_filter: { timestamptzArray: { zzz_notDistinctFrom: $v2 } }
  ) {
    ...nodes
  }
  notEqualTo: allArrayTypes(zzz_filter: { timestamptzArray: { zzz_notEqualTo: $v2 } }) {
    ...nodes
  }
  overlaps: allArrayTypes(zzz_filter: { timestamptzArray: { zzz_overlaps: $v2 } }) {
    ...nodes
  }
}

fragment nodes on ArrayTypesConnection {
  nodes {
    id
  }
}
