query {
  computed_equalTo_test_computed: allFilterables(zzz_filter: { computed: { zzz_equalTo: "test computed" } }) { ...computedConnection }
  computed_equalTo_test_computed_with_optional: allFilterables(zzz_filter: { computedWithOptional: { zzz_equalTo: "test default" } }) { ...computedConnection }
  computedIntArray_equalTo_2_20: allFilterables(zzz_filter: { computedIntArray: { zzz_equalTo: [2, 20] } }) { ...computedConnection }
  computedIntArray_equalTo_empty: allFilterables(zzz_filter: { computedIntArray: { zzz_equalTo: [] } }) { ...computedConnection }
  allFilterables_computedSetofChild_name_equalTo_child2: allFilterables { nodes { id, computedSetofChild(zzz_filter: { name: { zzz_equalTo: "child2" } }) { ...childConnection } } }
  filterableById_1_computedSetofChild_name_equalTo_child2: filterableById(id: 1) { id, computedSetofChild(zzz_filter: { name: { zzz_equalTo: "child2" } }) { ...childConnection } }
}

fragment computedConnection on FilterablesConnection {
  nodes {
    id
  }
}

fragment childConnection on ChildrenConnection {
  nodes {
    id
  }
}
