query dateDomain($v2: DateDomain = "1999-02-01", $v3: DateDomain = "1999-03-01") {
  distinctFrom: allDomainTypes(zzz_filter: { dateDomain: { zzz_distinctFrom: $v2 } }) {
    ...nodes
  }
  equalTo: allDomainTypes(zzz_filter: { dateDomain: { zzz_equalTo: $v2 } }) {
    ...nodes
  }
  greaterThan: allDomainTypes(zzz_filter: { dateDomain: { zzz_greaterThan: $v2 } }) {
    ...nodes
  }
  greaterThanOrEqualTo: allDomainTypes(
    zzz_filter: { dateDomain: { zzz_greaterThanOrEqualTo: $v2 } }
  ) {
    ...nodes
  }
  in: allDomainTypes(zzz_filter: { dateDomain: { zzz_in: [$v2, $v3] } }) {
    ...nodes
  }
  isNull: allDomainTypes(zzz_filter: { dateDomain: { zzz_isNull: true } }) {
    ...nodes
  }
  lessThan: allDomainTypes(zzz_filter: { dateDomain: { zzz_lessThan: $v2 } }) {
    ...nodes
  }
  lessThanOrEqualTo: allDomainTypes(
    zzz_filter: { dateDomain: { zzz_lessThanOrEqualTo: $v2 } }
  ) {
    ...nodes
  }
  notDistinctFrom: allDomainTypes(
    zzz_filter: { dateDomain: { zzz_notDistinctFrom: $v2 } }
  ) {
    ...nodes
  }
  notEqualTo: allDomainTypes(zzz_filter: { dateDomain: { zzz_notEqualTo: $v2 } }) {
    ...nodes
  }
  notIn: allDomainTypes(zzz_filter: { dateDomain: { zzz_notIn: [$v2] } }) {
    ...nodes
  }
}

fragment nodes on DomainTypesConnection {
  nodes {
    id
  }
}
