query int4Domain($v2: Int4Domain = 2, $v3: Int4Domain = 3) {
  distinctFrom: allDomainTypes(zzz_filter: { int4Domain: { zzz_distinctFrom: $v2 } }) {
    ...nodes
  }
  equalTo: allDomainTypes(zzz_filter: { int4Domain: { zzz_equalTo: $v2 } }) {
    ...nodes
  }
  greaterThan: allDomainTypes(zzz_filter: { int4Domain: { zzz_greaterThan: $v2 } }) {
    ...nodes
  }
  greaterThanOrEqualTo: allDomainTypes(
    zzz_filter: { int4Domain: { zzz_greaterThanOrEqualTo: $v2 } }
  ) {
    ...nodes
  }
  in: allDomainTypes(zzz_filter: { int4Domain: { zzz_in: [$v2, $v3] } }) {
    ...nodes
  }
  isNull: allDomainTypes(zzz_filter: { int4Domain: { zzz_isNull: true } }) {
    ...nodes
  }
  lessThan: allDomainTypes(zzz_filter: { int4Domain: { zzz_lessThan: $v2 } }) {
    ...nodes
  }
  lessThanOrEqualTo: allDomainTypes(
    zzz_filter: { int4Domain: { zzz_lessThanOrEqualTo: $v2 } }
  ) {
    ...nodes
  }
  notDistinctFrom: allDomainTypes(
    zzz_filter: { int4Domain: { zzz_notDistinctFrom: $v2 } }
  ) {
    ...nodes
  }
  notEqualTo: allDomainTypes(zzz_filter: { int4Domain: { zzz_notEqualTo: $v2 } }) {
    ...nodes
  }
  notIn: allDomainTypes(zzz_filter: { int4Domain: { zzz_notIn: [$v2] } }) {
    ...nodes
  }
}

fragment nodes on DomainTypesConnection {
  nodes {
    id
  }
}
