query dynamicJsonTrue(
  $varInt: Int = 2
  $varJSON: JSON = { key2: 2 }
  $varJSONFilter: JSONFilter = { zzz_contains: { key2: 2 } }
  $withArrayV2: JSON = [{ key2: 2 }, { key3: 3 }]
  $withObjectV2: JSON = { key2: 2 }
) {
  # The first four (a, b, c, d) should result in the same value
  a: allJsonbTests(zzz_filter: { jsonbWithObject: { zzz_contains: { key2: 2 } } }) {
    ...nodes
  }
  b: allJsonbTests(
    zzz_filter: { jsonbWithObject: { zzz_contains: { key2: $varInt } } }
  ) {
    ...nodes
  }
  c: allJsonbTests(zzz_filter: { jsonbWithObject: { zzz_contains: $varJSON } }) {
    ...nodes
  }
  d: allJsonbTests(zzz_filter: { jsonbWithObject: $varJSONFilter }) {
    ...nodes
  }
  withArray: allJsonbTests(
    zzz_filter: { jsonbWithArray: { zzz_equalTo: $withArrayV2 } }
  ) {
    ...nodes
  }
  withObject: allJsonbTests(
    zzz_filter: { jsonbWithObject: { zzz_equalTo: $withObjectV2 } }
  ) {
    ...nodes
  }
}

fragment nodes on JsonbTestsConnection {
  nodes {
    id
  }
}
