query enum($val: Mood = OK) {
  distinctFrom: allEnumTypes(zzz_filter: { enum: { zzz_distinctFrom: $val } }) {
    ...nodes
  }
  equalTo: allEnumTypes(zzz_filter: { enum: { zzz_equalTo: $val } }) {
    ...nodes
  }
  in: allEnumTypes(zzz_filter: { enum: { zzz_in: [$val] } }) {
    ...nodes
  }
  isNull: allEnumTypes(zzz_filter: { enum: { zzz_isNull: true } }) {
    ...nodes
  }
  notDistinctFrom: allEnumTypes(zzz_filter: { enum: { zzz_notDistinctFrom: $val } }) {
    ...nodes
  }
  notEqualTo: allEnumTypes(zzz_filter: { enum: { zzz_notEqualTo: $val } }) {
    ...nodes
  }
  notIn: allEnumTypes(zzz_filter: { enum: { zzz_notIn: [$val] } }) {
    ...nodes
  }
}

fragment nodes on EnumTypesConnection {
  nodes {
    id
  }
}
