# All queries in this file should result in no filter being applied, thus returning all rows
# (queries are an exact copy of nullAndEmptyForbidden.graphql)
query ($undefined: String, $null: String = null) {
  a: allFilterables(zzz_filter: null) {
    totalCount
  }
  b: allFilterables(zzz_filter: {}) {
    totalCount
  }
  c: allFilterables(zzz_filter: { text: null }) {
    totalCount
  }
  d: allFilterables(zzz_filter: { text: {} }) {
    totalCount
  }
  e: allFilterables(zzz_filter: { text: null, int4: null }) {
    totalCount
  }
  f: allFilterables(zzz_filter: { text: {}, int4: {} }) {
    totalCount
  }
  g: allFilterables(zzz_filter: { text: null, int4: {} }) {
    totalCount
  }
  h: allFilterables(zzz_filter: { text: { zzz_equalTo: null } }) {
    totalCount
  }
  i: allFilterables(zzz_filter: { text: { zzz_equalTo: null, zzz_notEqualTo: null } }) {
    totalCount
  }
  j: allFilterables(
    zzz_filter: {
      text: { zzz_equalTo: null, zzz_notEqualTo: null }
      int4: { zzz_equalTo: null }
      numeric: {}
      bool: null
    }
  ) {
    totalCount
  }
  k: allFilterables(zzz_filter: { zzz_and: null }) {
    totalCount
  }
  l: allFilterables(zzz_filter: { zzz_and: [{}] }) {
    totalCount
  }
  m: allFilterables(zzz_filter: { zzz_and: [{}, {}] }) {
    totalCount
  }
  n: allFilterables(zzz_filter: { zzz_or: null }) {
    totalCount
  }
  o: allFilterables(zzz_filter: { zzz_or: [{}] }) {
    totalCount
  }
  p: allFilterables(zzz_filter: { zzz_or: [{}, {}] }) {
    totalCount
  }
  q: allFilterables(zzz_filter: { zzz_not: null }) {
    totalCount
  }
  r: allFilterables(zzz_filter: { zzz_not: {} }) {
    totalCount
  }
  s: allFilterables(zzz_filter: { zzz_not: { text: null } }) {
    totalCount
  }
  t: allFilterables(zzz_filter: { zzz_not: { text: {} } }) {
    totalCount
  }
  forward_name_unfiltered: allFilterables {
    ...textConnection
  }
  forward_name_equalTo_forward2: allFilterables(
    zzz_filter: { forwardByForwardId: { name: { zzz_equalTo: "forward2" } } }
  ) {
    ...textConnection
  }
  forward_name_equalTo_null: allFilterables(
    zzz_filter: { forwardByForwardId: { name: { zzz_equalTo: null } } }
  ) {
    ...textConnection
  }
  forward_name_equalTo_undefined: allFilterables(
    zzz_filter: { forwardByForwardId: { name: { zzz_equalTo: $undefined } } }
  ) {
    ...textConnection
  }
  backward_name_equalTo_null: allFilterables(
    zzz_filter: { backwardByFilterableId: { name: { zzz_equalTo: $null } } }
  ) {
    totalCount
  }
  backward_name_equalTo_null_in_or: allFilterables(
    zzz_filter: { zzz_or: [{ backwardByFilterableId: { name: { zzz_equalTo: $null } } }] }
  ) {
    totalCount
  }
  backward_name_equalTo_null_or_text_equalTo_Test_or_int4_equalTo_4: allFilterables(
    zzz_filter: {
      zzz_or: [
        { backwardByFilterableId: { name: { zzz_equalTo: $null } } }
        { text: { zzz_equalTo: "Test" } }
        { int4: { zzz_equalTo: 4 } }
      ]
    }
  ) {
    totalCount
  }
  not_empty_object: allFilterables(zzz_filter: { zzz_not: {} }) {
    totalCount
  }
  children_unfiltered: allFilterables {
    ...childrenConnection
  }
  children_every_name_equalTo_null: allFilterables(
    zzz_filter: { childrenByFilterableId: { every: { name: { zzz_equalTo: $null } } } }
  ) {
    totalCount
  }
  children_some_name_equalTo_child2: allFilterables(
    zzz_filter: {
      childrenByFilterableId: { some: { name: { zzz_equalTo: "child2" } } }
    }
  ) {
    ...childrenConnection
  }
  children_some_name_equalTo_null: allFilterables(
    zzz_filter: { childrenByFilterableId: { some: { name: { zzz_equalTo: $null } } } }
  ) {
    ...childrenConnection
  }
  children_some_name_equalTo_undefined: allFilterables(
    zzz_filter: {
      childrenByFilterableId: { some: { name: { zzz_equalTo: $undefined } } }
    }
  ) {
    ...childrenConnection
  }
  children_none_name_equalTo_child2: allFilterables(
    zzz_filter: {
      childrenByFilterableId: { none: { name: { zzz_equalTo: "child2" } } }
    }
  ) {
    ...childrenConnection
  }
  children_none_name_equalTo_null: allFilterables(
    zzz_filter: { childrenByFilterableId: { none: { name: { zzz_equalTo: $null } } } }
  ) {
    ...childrenConnection
  }
  children_none_name_equalTo_undefined: allFilterables(
    zzz_filter: {
      childrenByFilterableId: { none: { name: { zzz_equalTo: $undefined } } }
    }
  ) {
    ...childrenConnection
  }
}

fragment textConnection on FilterablesConnection {
  nodes {
    id
    text
  }
}

fragment childrenConnection on FilterablesConnection {
  nodes {
    id
    childrenByFilterableId {
      nodes {
        id
        name
      }
    }
  }
}
