query int4RangeArray(
  $v2: [IntRangeInput] = [
    {
      start: { value: 2, inclusive: true }
      end: { value: 3, inclusive: false }
    },
    {
      start: { value: 3, inclusive: true }
      end: { value: 4, inclusive: false }
    }
  ]
  $v2_1: IntRangeInput = {
    start: { value: 2, inclusive: true }
    end: { value: 3, inclusive: false }
  }
  $v3: [IntRangeInput] = [
    {
      start: { value: 3, inclusive: true }
      end: { value: 4, inclusive: false }
    },
    {
      start: { value: 4, inclusive: true }
      end: { value: 5, inclusive: false }
    }
  ]
) {
  anyEqualTo: allRangeArrayTypes(zzz_filter: { int4RangeArray: { zzz_anyEqualTo: $v2_1 } }) {
    ...nodes
  }
  anyGreaterThan: allRangeArrayTypes(
    zzz_filter: { int4RangeArray: { zzz_anyGreaterThan: $v2_1 } }
  ) {
    ...nodes
  }
  anyGreaterThanOrEqualTo: allRangeArrayTypes(
    zzz_filter: { int4RangeArray: { zzz_anyGreaterThanOrEqualTo: $v2_1 } }
  ) {
    ...nodes
  }
  anyLessThan: allRangeArrayTypes(zzz_filter: { int4RangeArray: { zzz_anyLessThan: $v2_1 } }) {
    ...nodes
  }
  anyLessThanOrEqualTo: allRangeArrayTypes(
    zzz_filter: { int4RangeArray: { zzz_anyLessThanOrEqualTo: $v2_1 } }
  ) {
    ...nodes
  }
  anyNotEqualTo: allRangeArrayTypes(
    zzz_filter: { int4RangeArray: { zzz_anyNotEqualTo: $v2_1 } }
  ) {
    ...nodes
  }
  containedBy: allRangeArrayTypes(zzz_filter: { int4RangeArray: { zzz_containedBy: $v2 } }) {
    ...nodes
  }
  contains: allRangeArrayTypes(zzz_filter: { int4RangeArray: { zzz_contains: $v3 } }) {
    ...nodes
  }
  distinctFrom: allRangeArrayTypes(zzz_filter: { int4RangeArray: { zzz_distinctFrom: $v2 } }) {
    ...nodes
  }
  equalTo: allRangeArrayTypes(zzz_filter: { int4RangeArray: { zzz_equalTo: $v2 } }) {
    ...nodes
  }
  greaterThan: allRangeArrayTypes(zzz_filter: { int4RangeArray: { zzz_greaterThan: $v2 } }) {
    ...nodes
  }
  greaterThanOrEqualTo: allRangeArrayTypes(
    zzz_filter: { int4RangeArray: { zzz_greaterThanOrEqualTo: $v2 } }
  ) {
    ...nodes
  }
  isNull: allRangeArrayTypes(zzz_filter: { int4RangeArray: { zzz_isNull: true } }) {
    ...nodes
  }
  lessThan: allRangeArrayTypes(zzz_filter: { int4RangeArray: { zzz_lessThan: $v2 } }) {
    ...nodes
  }
  lessThanOrEqualTo: allRangeArrayTypes(
    zzz_filter: { int4RangeArray: { zzz_lessThanOrEqualTo: $v2 } }
  ) {
    ...nodes
  }
  notDistinctFrom: allRangeArrayTypes(
    zzz_filter: { int4RangeArray: { zzz_notDistinctFrom: $v2 } }
  ) {
    ...nodes
  }
  notEqualTo: allRangeArrayTypes(zzz_filter: { int4RangeArray: { zzz_notEqualTo: $v2 } }) {
    ...nodes
  }
  overlaps: allRangeArrayTypes(zzz_filter: { int4RangeArray: { zzz_overlaps: $v2 } }) {
    ...nodes
  }
}

fragment nodes on RangeArrayTypesConnection {
  nodes {
    id
  }
}
