query dateRange(
  $val: DateRangeInput = {
    start: { value: "1999-02-01", inclusive: true }
    end: { value: "1999-03-01", inclusive: false }
  }
  $elementVal: Date = "1999-02-01"
) {
  adjacentTo: allRangeTypes(zzz_filter: { dateRange: { zzz_adjacentTo: $val } }) {
    ...nodes
  }
  containedBy: allRangeTypes(zzz_filter: { dateRange: { zzz_containedBy: $val } }) {
    ...nodes
  }
  contains: allRangeTypes(zzz_filter: { dateRange: { zzz_contains: $val } }) {
    ...nodes
  }
  containsElement: allRangeTypes(
    zzz_filter: { dateRange: { zzz_containsElement: $elementVal } }
  ) {
    ...nodes
  }
  distinctFrom: allRangeTypes(zzz_filter: { dateRange: { zzz_distinctFrom: $val } }) {
    ...nodes
  }
  equalTo: allRangeTypes(zzz_filter: { dateRange: { zzz_equalTo: $val } }) {
    ...nodes
  }
  in: allRangeTypes(zzz_filter: { dateRange: { zzz_in: [$val] } }) {
    ...nodes
  }
  isNull: allRangeTypes(zzz_filter: { dateRange: { zzz_isNull: true } }) {
    ...nodes
  }
  notDistinctFrom: allRangeTypes(
    zzz_filter: { dateRange: { zzz_notDistinctFrom: $val } }
  ) {
    ...nodes
  }
  notEqualTo: allRangeTypes(zzz_filter: { dateRange: { zzz_notEqualTo: $val } }) {
    ...nodes
  }
  notExtendsLeftOf: allRangeTypes(
    zzz_filter: { dateRange: { zzz_notExtendsLeftOf: $val } }
  ) {
    ...nodes
  }
  notExtendsRightOf: allRangeTypes(
    zzz_filter: { dateRange: { zzz_notExtendsRightOf: $val } }
  ) {
    ...nodes
  }
  notIn: allRangeTypes(zzz_filter: { dateRange: { zzz_notIn: [$val] } }) {
    ...nodes
  }
  overlaps: allRangeTypes(zzz_filter: { dateRange: { zzz_overlaps: $val } }) {
    ...nodes
  }
  strictlyLeftOf: allRangeTypes(
    zzz_filter: { dateRange: { zzz_strictlyLeftOf: $val } }
  ) {
    ...nodes
  }
  strictlyRightOf: allRangeTypes(
    zzz_filter: { dateRange: { zzz_strictlyRightOf: $val } }
  ) {
    ...nodes
  }
}

fragment nodes on RangeTypesConnection {
  nodes {
    id
  }
}
