query timestamp(
  $v2: Datetime = "1999-02-01 00:00"
  $v3: Datetime = "1999-03-01 00:00"
) {
  distinctFrom: allFilterables(zzz_filter: { timestamp: { zzz_distinctFrom: $v2 } }) {
    ...nodes
  }
  equalTo: allFilterables(zzz_filter: { timestamp: { zzz_equalTo: $v2 } }) {
    ...nodes
  }
  greaterThan: allFilterables(zzz_filter: { timestamp: { zzz_greaterThan: $v2 } }) {
    ...nodes
  }
  greaterThanOrEqualTo: allFilterables(
    zzz_filter: { timestamp: { zzz_greaterThanOrEqualTo: $v2 } }
  ) {
    ...nodes
  }
  in: allFilterables(zzz_filter: { timestamp: { zzz_in: [$v2, $v3] } }) {
    ...nodes
  }
  isNull: allFilterables(zzz_filter: { timestamp: { zzz_isNull: true } }) {
    ...nodes
  }
  lessThan: allFilterables(zzz_filter: { timestamp: { zzz_lessThan: $v2 } }) {
    ...nodes
  }
  lessThanOrEqualTo: allFilterables(
    zzz_filter: { timestamp: { zzz_lessThanOrEqualTo: $v2 } }
  ) {
    ...nodes
  }
  notDistinctFrom: allFilterables(zzz_filter: { timestamp: { zzz_notDistinctFrom: $v2 } }) {
    ...nodes
  }
  notEqualTo: allFilterables(zzz_filter: { timestamp: { zzz_notEqualTo: $v2 } }) {
    ...nodes
  }
  notIn: allFilterables(zzz_filter: { timestamp: { zzz_notIn: [$v2] } }) {
    ...nodes
  }
}

fragment nodes on FilterablesConnection {
  nodes {
    id
  }
}
