query hstore(
  $v2: KeyValueHash = {key2:"2"}
  $v2_1_key: String = "key2"
  $v3: KeyValueHash = {key3:"3"}
  $v3_1_key: String = "key3"
) {
  containedBy: allFilterables(zzz_filter: { hstore: { zzz_containedBy: $v2 } }) {
    ...nodes
  }
  contains: allFilterables(zzz_filter: { hstore: { zzz_contains: $v3 } }) {
    ...nodes
  }
  containsAllKeys: allFilterables(
    zzz_filter: { hstore: { zzz_containsAllKeys: [$v2_1_key] } }
  ) {
    ...nodes
  }
  containsAnyKeys: allFilterables(
    zzz_filter: { hstore: { zzz_containsAnyKeys: [$v2_1_key, $v3_1_key] } }
  ) {
    ...nodes
  }
  containsKey: allFilterables(zzz_filter: { hstore: { zzz_containsKey: $v2_1_key } }) {
    ...nodes
  }
  distinctFrom: allFilterables(zzz_filter: { hstore: { zzz_distinctFrom: $v2 } }) {
    ...nodes
  }
  equalTo: allFilterables(zzz_filter: { hstore: { zzz_equalTo: $v2 } }) {
    ...nodes
  }
  in: allFilterables(zzz_filter: { hstore: { zzz_in: [$v2, $v3] } }) {
    ...nodes
  }
  isNull: allFilterables(zzz_filter: { hstore: { zzz_isNull: true } }) {
    ...nodes
  }
  notDistinctFrom: allFilterables(
    zzz_filter: { hstore: { zzz_notDistinctFrom: $v2 } }
  ) {
    ...nodes
  }
  notEqualTo: allFilterables(zzz_filter: { hstore: { zzz_notEqualTo: $v2 } }) {
    ...nodes
  }
  notIn: allFilterables(zzz_filter: { hstore: { zzz_notIn: [$v2] } }) {
    ...nodes
  }
}

fragment nodes on FilterablesConnection {
  nodes {
    id
  }
}
