query inet(
  $v2: InternetAddress = "192.168.1.2"
  $v3: InternetAddress = "192.168.1.3"
) {
  containedBy: allFilterables(zzz_filter: { inet: { zzz_containedBy: $v2 } }) {
    ...nodes
  }
  containedByOrEqualTo: allFilterables(
    zzz_filter: { inet: { zzz_containedByOrEqualTo: $v2 } }
  ) {
    ...nodes
  }
  contains: allFilterables(zzz_filter: { inet: { zzz_contains: $v2 } }) {
    ...nodes
  }
  containsOrContainedBy: allFilterables(
    zzz_filter: { inet: { zzz_containsOrContainedBy: $v2 } }
  ) {
    ...nodes
  }
  containsOrEqualTo: allFilterables(
    zzz_filter: { inet: { zzz_containsOrEqualTo: $v2 } }
  ) {
    ...nodes
  }
  distinctFrom: allFilterables(zzz_filter: { inet: { zzz_distinctFrom: $v2 } }) {
    ...nodes
  }
  equalTo: allFilterables(zzz_filter: { inet: { zzz_equalTo: $v2 } }) {
    ...nodes
  }
  greaterThan: allFilterables(zzz_filter: { inet: { zzz_greaterThan: $v2 } }) {
    ...nodes
  }
  greaterThanOrEqualTo: allFilterables(
    zzz_filter: { inet: { zzz_greaterThanOrEqualTo: $v2 } }
  ) {
    ...nodes
  }
  in: allFilterables(zzz_filter: { inet: { zzz_in: [$v2, $v3] } }) {
    ...nodes
  }
  isNull: allFilterables(zzz_filter: { inet: { zzz_isNull: true } }) {
    ...nodes
  }
  lessThan: allFilterables(zzz_filter: { inet: { zzz_lessThan: $v2 } }) {
    ...nodes
  }
  lessThanOrEqualTo: allFilterables(
    zzz_filter: { inet: { zzz_lessThanOrEqualTo: $v2 } }
  ) {
    ...nodes
  }
  notDistinctFrom: allFilterables(zzz_filter: { inet: { zzz_notDistinctFrom: $v2 } }) {
    ...nodes
  }
  notEqualTo: allFilterables(zzz_filter: { inet: { zzz_notEqualTo: $v2 } }) {
    ...nodes
  }
  notIn: allFilterables(zzz_filter: { inet: { zzz_notIn: [$v2] } }) {
    ...nodes
  }
}

fragment nodes on FilterablesConnection {
  nodes {
    id
  }
}
