query money($v2: Float = 0.2, $v3: Float = 0.3) {
  distinctFrom: allFilterables(zzz_filter: { money: { zzz_distinctFrom: $v2 } }) {
    ...nodes
  }
  equalTo: allFilterables(zzz_filter: { money: { zzz_equalTo: $v2 } }) {
    ...nodes
  }
  greaterThan: allFilterables(zzz_filter: { money: { zzz_greaterThan: $v2 } }) {
    ...nodes
  }
  greaterThanOrEqualTo: allFilterables(
    zzz_filter: { money: { zzz_greaterThanOrEqualTo: $v2 } }
  ) {
    ...nodes
  }
  in: allFilterables(zzz_filter: { money: { zzz_in: [$v2, $v3] } }) {
    ...nodes
  }
  isNull: allFilterables(zzz_filter: { money: { zzz_isNull: true } }) {
    ...nodes
  }
  lessThan: allFilterables(zzz_filter: { money: { zzz_lessThan: $v2 } }) {
    ...nodes
  }
  lessThanOrEqualTo: allFilterables(
    zzz_filter: { money: { zzz_lessThanOrEqualTo: $v2 } }
  ) {
    ...nodes
  }
  notDistinctFrom: allFilterables(zzz_filter: { money: { zzz_notDistinctFrom: $v2 } }) {
    ...nodes
  }
  notEqualTo: allFilterables(zzz_filter: { money: { zzz_notEqualTo: $v2 } }) {
    ...nodes
  }
  notIn: allFilterables(zzz_filter: { money: { zzz_notIn: [$v2] } }) {
    ...nodes
  }
}

fragment nodes on FilterablesConnection {
  nodes {
    id
  }
}
