query interval(
  $v2: IntervalInput = {
    seconds: 0
    minutes: 0
    hours: 0
    days: 2
    months: 0
    years: 0
  }
  $v3: IntervalInput = {
    seconds: 0
    minutes: 0
    hours: 0
    days: 3
    months: 0
    years: 0
  }
) {
  distinctFrom: allFilterables(zzz_filter: { interval: { zzz_distinctFrom: $v2 } }) {
    ...nodes
  }
  equalTo: allFilterables(zzz_filter: { interval: { zzz_equalTo: $v2 } }) {
    ...nodes
  }
  greaterThan: allFilterables(zzz_filter: { interval: { zzz_greaterThan: $v2 } }) {
    ...nodes
  }
  greaterThanOrEqualTo: allFilterables(
    zzz_filter: { interval: { zzz_greaterThanOrEqualTo: $v2 } }
  ) {
    ...nodes
  }
  in: allFilterables(zzz_filter: { interval: { zzz_in: [$v2, $v3] } }) {
    ...nodes
  }
  isNull: allFilterables(zzz_filter: { interval: { zzz_isNull: true } }) {
    ...nodes
  }
  lessThan: allFilterables(zzz_filter: { interval: { zzz_lessThan: $v2 } }) {
    ...nodes
  }
  lessThanOrEqualTo: allFilterables(
    zzz_filter: { interval: { zzz_lessThanOrEqualTo: $v2 } }
  ) {
    ...nodes
  }
  notDistinctFrom: allFilterables(
    zzz_filter: { interval: { zzz_notDistinctFrom: $v2 } }
  ) {
    ...nodes
  }
  notEqualTo: allFilterables(zzz_filter: { interval: { zzz_notEqualTo: $v2 } }) {
    ...nodes
  }
  notIn: allFilterables(zzz_filter: { interval: { zzz_notIn: [$v2] } }) {
    ...nodes
  }
}

fragment nodes on FilterablesConnection {
  nodes {
    id
  }
}
