query name($v2: String = "Test", $v3: String = "tEST") {
  distinctFrom: allFilterables(zzz_filter: { name: { zzz_distinctFrom: $v2 } }) {
    ...nodes
  }
  distinctFromInsensitive: allFilterables(zzz_filter: { name: { zzz_distinctFromInsensitive: $v2 } }) {
    ...nodes
  }
  endsWith: allFilterables(zzz_filter: { name: { zzz_endsWith: "T" } }) {
    ...nodes
  }
  endsWithInsensitive: allFilterables(
    zzz_filter: { name: { zzz_endsWithInsensitive: "T" } }
  ) {
    ...nodes
  }
  equalTo: allFilterables(zzz_filter: { name: { zzz_equalTo: $v2 } }) {
    ...nodes
  }
  equalToInsensitive: allFilterables(zzz_filter: { name: { zzz_equalToInsensitive: $v2 } }) {
    ...nodes
  }
  greaterThan: allFilterables(zzz_filter: { name: { zzz_greaterThan: $v2 } }) {
    ...nodes
  }
  greaterThanInsensitive: allFilterables(zzz_filter: { name: { zzz_greaterThanInsensitive: $v2 } }) {
    ...nodes
  }
  greaterThanOrEqualTo: allFilterables(
    zzz_filter: { name: { zzz_greaterThanOrEqualTo: $v2 } }
  ) {
    ...nodes
  }
  greaterThanOrEqualToInsensitive: allFilterables(
    zzz_filter: { name: { zzz_greaterThanOrEqualToInsensitive: $v2 } }
  ) {
    ...nodes
  }
  in: allFilterables(zzz_filter: { name: { zzz_in: [$v2, $v3] } }) {
    ...nodes
  }
  inInsensitive: allFilterables(zzz_filter: { name: { zzz_inInsensitive: [$v2, $v3] } }) {
    ...nodes
  }
  includes: allFilterables(zzz_filter: { name: { zzz_includes: "T" } }) {
    ...nodes
  }
  includesInsensitive: allFilterables(
    zzz_filter: { name: { zzz_includesInsensitive: "T" } }
  ) {
    ...nodes
  }
  isNull: allFilterables(zzz_filter: { name: { zzz_isNull: true } }) {
    ...nodes
  }
  lessThan: allFilterables(zzz_filter: { name: { zzz_lessThan: $v2 } }) {
    ...nodes
  }
  lessThanInsensitive: allFilterables(zzz_filter: { name: { zzz_lessThanInsensitive: $v2 } }) {
    ...nodes
  }
  lessThanOrEqualTo: allFilterables(
    zzz_filter: { name: { zzz_lessThanOrEqualTo: $v2 } }
  ) {
    ...nodes
  }
  lessThanOrEqualToInsensitive: allFilterables(
    zzz_filter: { name: { zzz_lessThanOrEqualToInsensitive: $v2 } }
  ) {
    ...nodes
  }
  like: allFilterables(zzz_filter: { name: { zzz_like: "%ES%" } }) {
    ...nodes
  }
  likeInsensitive: allFilterables(
    zzz_filter: { name: { zzz_likeInsensitive: "%ES%" } }
  ) {
    ...nodes
  }
  notDistinctFrom: allFilterables(zzz_filter: { name: { zzz_notDistinctFrom: $v2 } }) {
    ...nodes
  }
  notDistinctFromInsensitive: allFilterables(zzz_filter: { name: { zzz_notDistinctFromInsensitive: $v2 } }) {
    ...nodes
  }
  notEndsWith: allFilterables(zzz_filter: { name: { zzz_notEndsWith: "T" } }) {
    ...nodes
  }
  notEndsWithInsensitive: allFilterables(
    zzz_filter: { name: { zzz_notEndsWithInsensitive: "T" } }
  ) {
    ...nodes
  }
  notEqualTo: allFilterables(zzz_filter: { name: { zzz_notEqualTo: $v2 } }) {
    ...nodes
  }
  notEqualToInsensitive: allFilterables(zzz_filter: { name: { zzz_notEqualToInsensitive: $v2 } }) {
    ...nodes
  }
  notIn: allFilterables(zzz_filter: { name: { zzz_notIn: [$v2] } }) {
    ...nodes
  }
  notInInsensitive: allFilterables(zzz_filter: { name: { zzz_notInInsensitive: [$v2] } }) {
    ...nodes
  }
  notIncludes: allFilterables(zzz_filter: { name: { zzz_notIncludes: "T" } }) {
    ...nodes
  }
  notIncludesInsensitive: allFilterables(
    zzz_filter: { name: { zzz_notIncludesInsensitive: "T" } }
  ) {
    ...nodes
  }
  notLike: allFilterables(zzz_filter: { name: { zzz_notLike: "%ES%" } }) {
    ...nodes
  }
  notLikeInsensitive: allFilterables(
    zzz_filter: { name: { zzz_notLikeInsensitive: "%ES%" } }
  ) {
    ...nodes
  }
  notStartsWith: allFilterables(zzz_filter: { name: { zzz_notStartsWith: "T" } }) {
    ...nodes
  }
  notStartsWithInsensitive: allFilterables(
    zzz_filter: { name: { zzz_notStartsWithInsensitive: "T" } }
  ) {
    ...nodes
  }
  startsWith: allFilterables(zzz_filter: { name: { zzz_startsWith: "T" } }) {
    ...nodes
  }
  startsWithInsensitive: allFilterables(
    zzz_filter: { name: { zzz_startsWithInsensitive: "T" } }
  ) {
    ...nodes
  }
}

fragment nodes on FilterablesConnection {
  nodes {
    id
  }
}
