import * as fs from "node:fs/promises";

const __dirname = import.meta.dirname;

const ROOT = `${__dirname}/..`;
const versionTsPath = `${ROOT}/src/version.ts`;
const packageJsonPath = `${ROOT}/package.json`;

const packageJson = JSON.parse(await fs.readFile(packageJsonPath, "utf8"));

await fs.writeFile(
  versionTsPath,
  `\
// This file is autogenerated by /scripts/postversion.mjs
export const version = ${JSON.stringify(packageJson.version)};
`
);
